### ISSUE TITLE
add web3.university in the learning resources 

### ISSUE THREAD

**Issue by kumar-kalyan** [hackbeats/complete-web3-bootcamp#16]

**Comment by Prakhar9450** [comment]
Please assign me this issue

**Comment by Azhar221** [comment]
have opened a pull request on it, please review it and let me know

**Comment by kumar-kalyan** [comment]
> have opened a pull request on it, please review it and let me know

 Please ask for assigning first this time I am merging it make sure next time you follow the protocols
