### ISSUE TITLE
Add beginner friendly articles to get stated wth web3

### ISSUE THREAD

**Issue by kumar-kalyan** [hackbeats/complete-web3-bootcamp#2]

**Comment by vishalpatil20** [comment]
Hey @kumar-kalyan i would love to contribute just mention where to add the articles.

**Comment by kumar-kalyan** [comment]
Create a file named articles. Md and just add article links follow ed by a
tldr

**Comment by issa-me-sush** [comment]
hey! could I contribute to this too? :D

**Comment by ayushigeorge** [comment]
I want to contribute to it as well!

**Comment by kumarixxii** [comment]
Hey  there can I work on this  ?

**Comment by kumar-kalyan** [comment]
> hey! could I contribute to this too? :D

go ahead

**Comment by kumar-kalyan** [comment]
> Hey there can I work on this ?

go ahead

**Comment by kumar-kalyan** [comment]
Sure!

**Comment by Prakhar9450** [comment]
Can I contribute to this issue
