### ISSUE TITLE
Fix Discord Link

### ISSUE THREAD

**Issue by uday03meh** [hackbeats/complete-web3-bootcamp#47]
I want to update discord's link in README as the current  one is showing this

![image](https://user-images.githubusercontent.com/59679281/194772987-228424be-9d29-4de5-b775-d27d6200b1b5.png)

Correct link : [Hack Beats](https://discord.gg/RJQ57S8NeF)

Also mentioned in issue #31 : https://github.com/hackbeats/complete-web3-bootcamp/pull/31#issuecomment-1272599156

**Comment by kumar-kalyan** [comment]
Go ahead
